/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as PrivpolicyRouteImport } from './routes/privpolicy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStoreRouteImport } from './routes/app/store'
import { Route as AppStatsRouteImport } from './routes/app/stats'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppMenuRouteImport } from './routes/app/menu'
import { Route as AppLeaderboardRouteImport } from './routes/app/leaderboard'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppExercisesRouteImport } from './routes/app/exercises'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivpolicyRoute = PrivpolicyRouteImport.update({
  id: '/privpolicy',
  path: '/privpolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privpolicy': typeof PrivpolicyRoute
  '/tos': typeof TosRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/menu': typeof AppMenuRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/store': typeof AppStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privpolicy': typeof PrivpolicyRoute
  '/tos': typeof TosRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/menu': typeof AppMenuRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/store': typeof AppStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privpolicy': typeof PrivpolicyRoute
  '/tos': typeof TosRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/menu': typeof AppMenuRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/store': typeof AppStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/privpolicy'
    | '/tos'
    | '/app/exercises'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/menu'
    | '/app/settings'
    | '/app/stats'
    | '/app/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/privpolicy'
    | '/tos'
    | '/app/exercises'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/menu'
    | '/app/settings'
    | '/app/stats'
    | '/app/store'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/privpolicy'
    | '/tos'
    | '/app/exercises'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/menu'
    | '/app/settings'
    | '/app/stats'
    | '/app/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivpolicyRoute: typeof PrivpolicyRoute
  TosRoute: typeof TosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privpolicy': {
      id: '/privpolicy'
      path: '/privpolicy'
      fullPath: '/privpolicy'
      preLoaderRoute: typeof PrivpolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercises': {
      id: '/app/exercises'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMenuRoute: typeof AppMenuRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppStoreRoute: typeof AppStoreRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMenuRoute: AppMenuRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppStoreRoute: AppStoreRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivpolicyRoute: PrivpolicyRoute,
  TosRoute: TosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
