/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as PrivpolicyRouteImport } from './routes/privpolicy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStoreRouteImport } from './routes/app/store'
import { Route as AppStatsRouteImport } from './routes/app/stats'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppMenuRouteImport } from './routes/app/menu'
import { Route as AppLeaderboardRouteImport } from './routes/app/leaderboard'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppExercisesRouteImport } from './routes/app/exercises'
import { Route as AppStoreToysRouteImport } from './routes/app/store/toys'
import { Route as AppStoreFoodRouteImport } from './routes/app/store/food'
import { Route as AppInventoryToysRouteImport } from './routes/app/inventory/toys'
import { Route as AppInventoryPowerupsRouteImport } from './routes/app/inventory/powerups'
import { Route as AppInventoryMedicineRouteImport } from './routes/app/inventory/medicine'
import { Route as AppInventoryFoodRouteImport } from './routes/app/inventory/food'
import { Route as AppStoreToysItemIdRouteImport } from './routes/app/store/toys.$itemId'
import { Route as AppStoreFoodItemIdRouteImport } from './routes/app/store/food.$itemId'
import { Route as AppInventoryToysItemIdRouteImport } from './routes/app/inventory/toys.$itemId'
import { Route as AppInventoryPowerupsItemIdRouteImport } from './routes/app/inventory/powerups.$itemId'
import { Route as AppInventoryMedicineItemIdRouteImport } from './routes/app/inventory/medicine.$itemId'
import { Route as AppInventoryFoodItemIdRouteImport } from './routes/app/inventory/food.$itemId'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivpolicyRoute = PrivpolicyRouteImport.update({
  id: '/privpolicy',
  path: '/privpolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreToysRoute = AppStoreToysRouteImport.update({
  id: '/toys',
  path: '/toys',
  getParentRoute: () => AppStoreRoute,
} as any)
const AppStoreFoodRoute = AppStoreFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AppStoreRoute,
} as any)
const AppInventoryToysRoute = AppInventoryToysRouteImport.update({
  id: '/toys',
  path: '/toys',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryPowerupsRoute = AppInventoryPowerupsRouteImport.update({
  id: '/powerups',
  path: '/powerups',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMedicineRoute = AppInventoryMedicineRouteImport.update({
  id: '/medicine',
  path: '/medicine',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryFoodRoute = AppInventoryFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppStoreToysItemIdRoute = AppStoreToysItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AppStoreToysRoute,
} as any)
const AppStoreFoodItemIdRoute = AppStoreFoodItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AppStoreFoodRoute,
} as any)
const AppInventoryToysItemIdRoute = AppInventoryToysItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AppInventoryToysRoute,
} as any)
const AppInventoryPowerupsItemIdRoute =
  AppInventoryPowerupsItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AppInventoryPowerupsRoute,
  } as any)
const AppInventoryMedicineItemIdRoute =
  AppInventoryMedicineItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AppInventoryMedicineRoute,
  } as any)
const AppInventoryFoodItemIdRoute = AppInventoryFoodItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AppInventoryFoodRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privpolicy': typeof PrivpolicyRoute
  '/tos': typeof TosRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/menu': typeof AppMenuRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/store': typeof AppStoreRouteWithChildren
  '/app/inventory/food': typeof AppInventoryFoodRouteWithChildren
  '/app/inventory/medicine': typeof AppInventoryMedicineRouteWithChildren
  '/app/inventory/powerups': typeof AppInventoryPowerupsRouteWithChildren
  '/app/inventory/toys': typeof AppInventoryToysRouteWithChildren
  '/app/store/food': typeof AppStoreFoodRouteWithChildren
  '/app/store/toys': typeof AppStoreToysRouteWithChildren
  '/app/inventory/food/$itemId': typeof AppInventoryFoodItemIdRoute
  '/app/inventory/medicine/$itemId': typeof AppInventoryMedicineItemIdRoute
  '/app/inventory/powerups/$itemId': typeof AppInventoryPowerupsItemIdRoute
  '/app/inventory/toys/$itemId': typeof AppInventoryToysItemIdRoute
  '/app/store/food/$itemId': typeof AppStoreFoodItemIdRoute
  '/app/store/toys/$itemId': typeof AppStoreToysItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privpolicy': typeof PrivpolicyRoute
  '/tos': typeof TosRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/menu': typeof AppMenuRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/store': typeof AppStoreRouteWithChildren
  '/app/inventory/food': typeof AppInventoryFoodRouteWithChildren
  '/app/inventory/medicine': typeof AppInventoryMedicineRouteWithChildren
  '/app/inventory/powerups': typeof AppInventoryPowerupsRouteWithChildren
  '/app/inventory/toys': typeof AppInventoryToysRouteWithChildren
  '/app/store/food': typeof AppStoreFoodRouteWithChildren
  '/app/store/toys': typeof AppStoreToysRouteWithChildren
  '/app/inventory/food/$itemId': typeof AppInventoryFoodItemIdRoute
  '/app/inventory/medicine/$itemId': typeof AppInventoryMedicineItemIdRoute
  '/app/inventory/powerups/$itemId': typeof AppInventoryPowerupsItemIdRoute
  '/app/inventory/toys/$itemId': typeof AppInventoryToysItemIdRoute
  '/app/store/food/$itemId': typeof AppStoreFoodItemIdRoute
  '/app/store/toys/$itemId': typeof AppStoreToysItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privpolicy': typeof PrivpolicyRoute
  '/tos': typeof TosRoute
  '/app/exercises': typeof AppExercisesRoute
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/menu': typeof AppMenuRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/store': typeof AppStoreRouteWithChildren
  '/app/inventory/food': typeof AppInventoryFoodRouteWithChildren
  '/app/inventory/medicine': typeof AppInventoryMedicineRouteWithChildren
  '/app/inventory/powerups': typeof AppInventoryPowerupsRouteWithChildren
  '/app/inventory/toys': typeof AppInventoryToysRouteWithChildren
  '/app/store/food': typeof AppStoreFoodRouteWithChildren
  '/app/store/toys': typeof AppStoreToysRouteWithChildren
  '/app/inventory/food/$itemId': typeof AppInventoryFoodItemIdRoute
  '/app/inventory/medicine/$itemId': typeof AppInventoryMedicineItemIdRoute
  '/app/inventory/powerups/$itemId': typeof AppInventoryPowerupsItemIdRoute
  '/app/inventory/toys/$itemId': typeof AppInventoryToysItemIdRoute
  '/app/store/food/$itemId': typeof AppStoreFoodItemIdRoute
  '/app/store/toys/$itemId': typeof AppStoreToysItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/privpolicy'
    | '/tos'
    | '/app/exercises'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/menu'
    | '/app/settings'
    | '/app/stats'
    | '/app/store'
    | '/app/inventory/food'
    | '/app/inventory/medicine'
    | '/app/inventory/powerups'
    | '/app/inventory/toys'
    | '/app/store/food'
    | '/app/store/toys'
    | '/app/inventory/food/$itemId'
    | '/app/inventory/medicine/$itemId'
    | '/app/inventory/powerups/$itemId'
    | '/app/inventory/toys/$itemId'
    | '/app/store/food/$itemId'
    | '/app/store/toys/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/privpolicy'
    | '/tos'
    | '/app/exercises'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/menu'
    | '/app/settings'
    | '/app/stats'
    | '/app/store'
    | '/app/inventory/food'
    | '/app/inventory/medicine'
    | '/app/inventory/powerups'
    | '/app/inventory/toys'
    | '/app/store/food'
    | '/app/store/toys'
    | '/app/inventory/food/$itemId'
    | '/app/inventory/medicine/$itemId'
    | '/app/inventory/powerups/$itemId'
    | '/app/inventory/toys/$itemId'
    | '/app/store/food/$itemId'
    | '/app/store/toys/$itemId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/privpolicy'
    | '/tos'
    | '/app/exercises'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/menu'
    | '/app/settings'
    | '/app/stats'
    | '/app/store'
    | '/app/inventory/food'
    | '/app/inventory/medicine'
    | '/app/inventory/powerups'
    | '/app/inventory/toys'
    | '/app/store/food'
    | '/app/store/toys'
    | '/app/inventory/food/$itemId'
    | '/app/inventory/medicine/$itemId'
    | '/app/inventory/powerups/$itemId'
    | '/app/inventory/toys/$itemId'
    | '/app/store/food/$itemId'
    | '/app/store/toys/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivpolicyRoute: typeof PrivpolicyRoute
  TosRoute: typeof TosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privpolicy': {
      id: '/privpolicy'
      path: '/privpolicy'
      fullPath: '/privpolicy'
      preLoaderRoute: typeof PrivpolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercises': {
      id: '/app/exercises'
      path: '/exercises'
      fullPath: '/app/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/store/toys': {
      id: '/app/store/toys'
      path: '/toys'
      fullPath: '/app/store/toys'
      preLoaderRoute: typeof AppStoreToysRouteImport
      parentRoute: typeof AppStoreRoute
    }
    '/app/store/food': {
      id: '/app/store/food'
      path: '/food'
      fullPath: '/app/store/food'
      preLoaderRoute: typeof AppStoreFoodRouteImport
      parentRoute: typeof AppStoreRoute
    }
    '/app/inventory/toys': {
      id: '/app/inventory/toys'
      path: '/toys'
      fullPath: '/app/inventory/toys'
      preLoaderRoute: typeof AppInventoryToysRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/powerups': {
      id: '/app/inventory/powerups'
      path: '/powerups'
      fullPath: '/app/inventory/powerups'
      preLoaderRoute: typeof AppInventoryPowerupsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/medicine': {
      id: '/app/inventory/medicine'
      path: '/medicine'
      fullPath: '/app/inventory/medicine'
      preLoaderRoute: typeof AppInventoryMedicineRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/food': {
      id: '/app/inventory/food'
      path: '/food'
      fullPath: '/app/inventory/food'
      preLoaderRoute: typeof AppInventoryFoodRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/store/toys/$itemId': {
      id: '/app/store/toys/$itemId'
      path: '/$itemId'
      fullPath: '/app/store/toys/$itemId'
      preLoaderRoute: typeof AppStoreToysItemIdRouteImport
      parentRoute: typeof AppStoreToysRoute
    }
    '/app/store/food/$itemId': {
      id: '/app/store/food/$itemId'
      path: '/$itemId'
      fullPath: '/app/store/food/$itemId'
      preLoaderRoute: typeof AppStoreFoodItemIdRouteImport
      parentRoute: typeof AppStoreFoodRoute
    }
    '/app/inventory/toys/$itemId': {
      id: '/app/inventory/toys/$itemId'
      path: '/$itemId'
      fullPath: '/app/inventory/toys/$itemId'
      preLoaderRoute: typeof AppInventoryToysItemIdRouteImport
      parentRoute: typeof AppInventoryToysRoute
    }
    '/app/inventory/powerups/$itemId': {
      id: '/app/inventory/powerups/$itemId'
      path: '/$itemId'
      fullPath: '/app/inventory/powerups/$itemId'
      preLoaderRoute: typeof AppInventoryPowerupsItemIdRouteImport
      parentRoute: typeof AppInventoryPowerupsRoute
    }
    '/app/inventory/medicine/$itemId': {
      id: '/app/inventory/medicine/$itemId'
      path: '/$itemId'
      fullPath: '/app/inventory/medicine/$itemId'
      preLoaderRoute: typeof AppInventoryMedicineItemIdRouteImport
      parentRoute: typeof AppInventoryMedicineRoute
    }
    '/app/inventory/food/$itemId': {
      id: '/app/inventory/food/$itemId'
      path: '/$itemId'
      fullPath: '/app/inventory/food/$itemId'
      preLoaderRoute: typeof AppInventoryFoodItemIdRouteImport
      parentRoute: typeof AppInventoryFoodRoute
    }
  }
}

interface AppInventoryFoodRouteChildren {
  AppInventoryFoodItemIdRoute: typeof AppInventoryFoodItemIdRoute
}

const AppInventoryFoodRouteChildren: AppInventoryFoodRouteChildren = {
  AppInventoryFoodItemIdRoute: AppInventoryFoodItemIdRoute,
}

const AppInventoryFoodRouteWithChildren =
  AppInventoryFoodRoute._addFileChildren(AppInventoryFoodRouteChildren)

interface AppInventoryMedicineRouteChildren {
  AppInventoryMedicineItemIdRoute: typeof AppInventoryMedicineItemIdRoute
}

const AppInventoryMedicineRouteChildren: AppInventoryMedicineRouteChildren = {
  AppInventoryMedicineItemIdRoute: AppInventoryMedicineItemIdRoute,
}

const AppInventoryMedicineRouteWithChildren =
  AppInventoryMedicineRoute._addFileChildren(AppInventoryMedicineRouteChildren)

interface AppInventoryPowerupsRouteChildren {
  AppInventoryPowerupsItemIdRoute: typeof AppInventoryPowerupsItemIdRoute
}

const AppInventoryPowerupsRouteChildren: AppInventoryPowerupsRouteChildren = {
  AppInventoryPowerupsItemIdRoute: AppInventoryPowerupsItemIdRoute,
}

const AppInventoryPowerupsRouteWithChildren =
  AppInventoryPowerupsRoute._addFileChildren(AppInventoryPowerupsRouteChildren)

interface AppInventoryToysRouteChildren {
  AppInventoryToysItemIdRoute: typeof AppInventoryToysItemIdRoute
}

const AppInventoryToysRouteChildren: AppInventoryToysRouteChildren = {
  AppInventoryToysItemIdRoute: AppInventoryToysItemIdRoute,
}

const AppInventoryToysRouteWithChildren =
  AppInventoryToysRoute._addFileChildren(AppInventoryToysRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryFoodRoute: typeof AppInventoryFoodRouteWithChildren
  AppInventoryMedicineRoute: typeof AppInventoryMedicineRouteWithChildren
  AppInventoryPowerupsRoute: typeof AppInventoryPowerupsRouteWithChildren
  AppInventoryToysRoute: typeof AppInventoryToysRouteWithChildren
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryFoodRoute: AppInventoryFoodRouteWithChildren,
  AppInventoryMedicineRoute: AppInventoryMedicineRouteWithChildren,
  AppInventoryPowerupsRoute: AppInventoryPowerupsRouteWithChildren,
  AppInventoryToysRoute: AppInventoryToysRouteWithChildren,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppStoreFoodRouteChildren {
  AppStoreFoodItemIdRoute: typeof AppStoreFoodItemIdRoute
}

const AppStoreFoodRouteChildren: AppStoreFoodRouteChildren = {
  AppStoreFoodItemIdRoute: AppStoreFoodItemIdRoute,
}

const AppStoreFoodRouteWithChildren = AppStoreFoodRoute._addFileChildren(
  AppStoreFoodRouteChildren,
)

interface AppStoreToysRouteChildren {
  AppStoreToysItemIdRoute: typeof AppStoreToysItemIdRoute
}

const AppStoreToysRouteChildren: AppStoreToysRouteChildren = {
  AppStoreToysItemIdRoute: AppStoreToysItemIdRoute,
}

const AppStoreToysRouteWithChildren = AppStoreToysRoute._addFileChildren(
  AppStoreToysRouteChildren,
)

interface AppStoreRouteChildren {
  AppStoreFoodRoute: typeof AppStoreFoodRouteWithChildren
  AppStoreToysRoute: typeof AppStoreToysRouteWithChildren
}

const AppStoreRouteChildren: AppStoreRouteChildren = {
  AppStoreFoodRoute: AppStoreFoodRouteWithChildren,
  AppStoreToysRoute: AppStoreToysRouteWithChildren,
}

const AppStoreRouteWithChildren = AppStoreRoute._addFileChildren(
  AppStoreRouteChildren,
)

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMenuRoute: typeof AppMenuRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppStoreRoute: typeof AppStoreRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMenuRoute: AppMenuRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppStoreRoute: AppStoreRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivpolicyRoute: PrivpolicyRoute,
  TosRoute: TosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
